//
//  MovieDetailInteractor.swift
//  PopCornFlix
//
//  Created by Burak Nurçiçek on 7.02.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MovieDetailInteractor {
}

// MARK: - Extensions -

extension MovieDetailInteractor: MovieDetailInteractorInterface {
}
