//
//  MovieDetailInterfaces.swift
//  PopCornFlix
//
//  Created by Burak Nurçiçek on 7.02.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MovieDetailWireframeInterface: WireframeInterface {
    func completedWithError()
}

protocol MovieDetailViewInterface: ViewInterface {
    func setMovieData(movie: Movie)
}

protocol MovieDetailPresenterInterface: PresenterInterface {
    func getMovieDetail(id: Int)
    func setMovieData(movie: Movie)
    func completedWithError()
    func addFavorite(id: Int)
}

protocol MovieDetailInteractorInterface: InteractorInterface {
    func getMovieDetail(id: Int)
}
