//
//  MovieInterfaces.swift
//  PopCornFlix
//
//  Created by Burak Nurçiçek on 7.02.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MovieWireframeInterface: WireframeInterface {
    func openMovieDetailModule()
}

protocol MovieViewInterface: ViewInterface {
    func setPopularMovies(movieList: MovieList)

}

protocol MoviePresenterInterface: PresenterInterface {
    func openMovieDetailModule()
    func getPopularMovies(pagination: Int)
    func completedWithError()
    func setPopularMovies(movieList: MovieList)

}

protocol MovieInteractorInterface: InteractorInterface {
    func getPopularMovies(pagination: Int)
}
