//
//  MovieWireframe.swift
//  PopCornFlix
//
//  Created by Burak Nurçiçek on 7.02.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MovieWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -
    init() {
        let moduleViewController = MovieViewController()
        super.init(viewController: moduleViewController)

        let interactor = MovieInteractor()
        let presenter = MoviePresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
        interactor.presenter = presenter
    }

}

// MARK: - Extensions -
extension MovieWireframe: MovieWireframeInterface {
    func openMovieDetailModule(data : MovieDetailWireFrameData) {
        self.navigationController?.pushWireframe(MovieDetailWireframe(data: data))
    }
}
